src/GlobalAssemblyInfo.cs
And keep file version as the full version number,
where the release segment will match the nuget
package patch.
=> Switch to using stable version # for the assembly

src/Clide/Solution/Implementation/Adapters/DteToSolutionAdapter.cs, src/Clide/Solution/Implementation/Adapters/DteToVsAdapter.cs
This is consistent with the way C# and VB project systems provide their
UniqueName, but we keep the DTE property retrieval in case other project
systems do it differently.
=> Fallback UniqueName to project full name if it fails

src/Clide.nuspec, src/Clide/Clide.csproj, src/Clide/DevEnvFactory.cs
This makes it far easier to diagnose composition errors.
When launching with `devenv /log`, upon constructing the MEF container
for a DevEnv for a given package/service provider, a Clide.[PACKAGEGUID].log
will be written to %LocalAppData%\Microsoft\VisualStudio\[VSVERSION][HIVE]\ComponentModelCache.
=> Dump MEF log when VS is started with /log switch

src/Clide.Interfaces/Solution/ISolutionNodeExtensions.cs
Returning false when we want to stop visiting nodes instead of throwing
an NotImplementedException.
When a project is unloaded in a solution, the IGenericNode is visited.
With the previous implementation we were throwing an exception instead
of just stopping the node visiting at the moment.
There is no advantage of throwing when the node is not supposed to
be visited. We just need to stop continue visiting the children at
that moment.
=> Fixed ProjectsVisitor to avoid throwing an exception for generic nodes

src/Clide.Interfaces/Startable/IStartable.cs, src/Clide.Interfaces/Startable/IStartableService.cs, src/Clide.Interfaces/Startable/StartableAttribute.cs, src/Clide.UnitTests/StartableServiceSpec.cs, src/Clide/Startable/IStartableMetadata.cs, src/Clide/Startable/StartableService.cs
Which allows a client to start components that matches a given context (string or Guid)
using the IStartableService and exporting the components using the Startable attribute.
=> Added Startable support

src/Clide.Interfaces/Adapters/SolutionAdapterFacade.cs, src/Clide.Interfaces/Adapters/VsAdapterFacade.cs, src/Clide.Interfaces/FlavoredProject.cs, src/Clide.Vsix/Clide.Vsix.csproj, src/Clide/Adapters/SolutionToVsAdapter.cs, src/Clide/Adapters/VsToSolutionAdapter.cs, src/Clide/Solution/ConfigProjectProperties.cs, src/Clide/Solution/ConfigUserProjectProperties.cs, src/Clide/Solution/GlobalProjectProperties.cs, src/Clide/Solution/ItemProperties.cs, src/Clide/Solution/ProjectNode.cs, src/Clide/Solution/SolutionExplorerNode.cs, src/Clide/Solution/UserProjectProperties.cs
Supporting also the case where the ProjectNode was adapted from a
flavored project where the InnerVsHierarchy should be used
to cast the IVsHierarchy to IVsBuildPropertyStorage
=> Added IProjectNode -> IVsBuildPropertyStorage adapter

src/Clide.Interfaces/Awaitable.cs
Instead of turning every async property into an GetXXXAsync
method, create instead a special-purpose class that prevents
doing the `.Result` anti-pattern and instead makes it trivial
to just `await Property` so that the API remains idiomatic.
We may expose analyzers that can hint at what awaitable
properties should run on the UI thread, for example.
=> Allow properties to be declared to be awaitable

src/Clide.Interfaces/Startable/StartableAttribute.cs
Some components might need to be started when any of the provided context are enabled.
So allowing multiple instances of the attribute unblocks this scenario:
[Startable("OnSolutionLoaded")]
[Startable("OnSettingsLoaded")]
public class MyComponent : IStartable {}
=> Allowing to use multiple instance of StartableAttribute

src/Clide.Interfaces/Startable/StartableAttribute.cs, src/Clide.UnitTests/StartableServiceSpec.cs, src/Clide/Startable/IStartableMetadata.cs, src/Clide/Startable/StartableService.cs
The context string can now contains multiple values separated by "|". e.g.
[Startable("OnSolutionLoad|{FFADDAAF-C12A-4426-B0E9-533A7AE8B27E}"]
It can also contains mixed string and guid values.
So the given startable component will be started when any of the following
IStartableService invocations occur:
startableService.StartComponentsAsync("OnSolutionLoad")
or
startableService.StartComponentsAsync("{FFADDAAF-C12A-4426-B0E9-533A7AE8B27E}")
=> Added support to define more than one startable context

src/Clide/Solution/ItemNode.cs
This fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/718419
Previously in dev16 the IVsHierarchy -> IVsProject cast returned null, at least
for a MonoAndroidFlavoredProject.
=> Properly convert IVsHierchy to IVsProject

src/Clide.Interfaces/Commands/CommandAttribute.cs, src/Clide.UnitTests/VsCommandExtensionAdapterSpec .cs, src/Clide/Commands/CommandRegistrar.cs, src/Clide/Commands/ICommandMetadata.cs, src/Clide/Commands/UIContextWrapper.cs, src/Clide/Commands/VsCommandExtensionAdapter.cs
Added an extra and optional argument to the CommandAttribute to define
the associated UI Context that should be active for the command
to be executed.
When the UI Context is not active neither the QueryStatus or the Execute
should be executed. And also the command should be disabled and invisible.
=> Added support to avoid Executing commands based on a given UI Context

src/Clide/Solution/ProjectNode.cs
- We should use the InnerHierarchy, if available, in case the ProjectNode represents the Flavored Hierarchy, because the later isn't the "real" Hierarchy and will make the Save fail.
- Added ThrowIfNotOnUIThread to ensure callers are running on the main thread since accessing the IVSSolution should only be done on that one.
=> Fixes ProjectNode Save method

src/Clide.Interfaces/DevEnvInfo.cs, src/Clide/DevEnvInfoProvider.cs, src/Clide/Interop/IVsAppId.cs
This information is needed to differentiate Release Candidate from Release versions, both ChannelTitle will be "Release", but the ChannelSuffix for the candidate one will be "RC".
=> Adds ChannelSuffix to DevEnvInfo

src/Clide/Solution/ProjectNode.cs
Using Hierarchy will get all the capabilities instead of getting only the ones from the inner hierarchy.
=> Fixes ProjectNode Supports method

src/Clide.IntegrationTests/AsyncManagerSpec.cs, src/Clide.IntegrationTests/DevEnvInfoProviderSpec.cs, src/Clide.IntegrationTests/Misc.cs, src/Clide/DevEnvInfoProvider.cs, src/Clide/Interop/IVsAppId.cs
In some cases, the SVs/IVs pattern is used to assign a service id (The SVs interface’s GUID) that differs from the ids of any interfaces it may happen to implement. Some times, it is just aliased to be the same id.
In this second case, declaring a dummy type with the same Guid is *not* needed, and it can moreover cause issues in the CLR as two COM types will end up having the same ID.
In service queries the only thing that matters is the GUIDs not the type, so for the purposes of GetService the types given are just a place to hang a GUID.
This commit removes the SVsAppId and replaces it with IVsAppId when queried.
=> Remove unnecessary SVsAppId

src/Clide/Adapters/VsToSolutionAdapter.cs
We must not call Get IVsHierarchyItemManager.GetHierarchyItem if the
corresponding IVsHierarchy is the flavored instance.
This commit fixes the base type we should have used to detect this case.
=> Using FlavoredProjectBase to check if we should use the IVsHierarchy

src/Clide/Solution/SolutionExplorerNode.cs
Before we were looking for the top most hierarchy item which in some
scenarios (project just loaded or debugging) was not working.
So we switch to ask the SolutionNode to the ISolutionExplorer which
already has an implementation using IVsSolution.
=> Ensure OwningSolution value by switching to IVsSolution usage

src/Clide/Solution/Factories/ReferencesNodeFactory.cs
This complements commit https://github.com/clariuslabs/clide/commit/422c15ce01b4817fab402dc4b3be3d103136ec9a
In order to avoid the creation of duplicate children we need to switch to the main
thread before calling IVsHierarchyItem.Children
And we also switched to use Any because the first item might be a PackageReference
which it does not provide an extender object.
=> Fixed usage of IVsHierarchyItem.Children in ReferencesNodeFactory

src/Clide/Solution/Factories/ProjectNodeFactory.cs
__VSPROPID4.VSPROPID_IsSolutionFullyLoaded must be called using the IVsSolution instance
=> Fixed usage of IsSolutionFullyLoaded in FixProjectNodeFactory

src/Clide.Extensibility/Solution/ISolutionExplorerNodeFactory.cs, src/Clide/Solution/Factories/SolutionExplorerNodeFactory.cs, src/Clide/Solution/SolutionExplorerNode.cs
The HierarchyManager was not implemented to be thread safe.
If the Nodes are being traversed from a background thread,
the caller might end up with a duplicate key/item exception.
So the proposal fix is to replace the existing implementation
by traversing the hierarchy using the legacy FirstChild/NextSibling
mechanism and switch to the main thread only when we need to
get/create the HierarchyItem.
=> Fixed the Nodes traversal

src/Clide.Extensibility/Solution/ISolutionExplorerNodeFactory.cs, src/Clide/Adapters/VsToSolutionAdapter.cs, src/Clide/Solution/Factories/SolutionExplorerNodeFactory.cs
When traversing nodes (or project nodes) we should first check if the
hierarchy item is already created before calling GetHierarchyItem which
requires to run in the main thread.
We achieve this by using ISolutionExplorerNodeFactory.CreateNode and passing
the IVsHierarchy as it was described in the following change:
https://github.com/clariuslabs/clide/commit/b90b856b199d99ea4891b6148cc6e563fbe45974
Fixes https://github.com/clariuslabs/clide/issues/141
=> Avoiding to switch to MainThread if not necessary

src/Clide.Interfaces/DialogCreated.cs, src/Clide/UI/DialogWindowFactory.cs
This will allow client to be notified when dialog instances
are created and execute and do proper stuff such as logging or
telemetry.
=> Pushing DialogCreated event when a dialog is created

src/Clide/Solution/ProjectConfiguration.cs
When comparing configuration context, the project full name is compared with the context's project name.
The problem is that the project in the context is a path relative to the solution, and the project full name is a rooted path.
The solution to that issue was to do EndsWith(), so we can see if the part of the path that the context name represents matches the rooted path. This will generally work, except when the project is not in the tree of the soltuion.
When the project is outside the solution, you may have values like this:
projectName = ..\App1\App1\App1.csproj
project.FullName = C:\Users\joaqu\source\repos\App70\App70\App70.csproj
The fix is to get the solution full name (which includes the path) and combine it with the context name.
I tested this with projects in the solution …
=> Rooted project path when comparing to find configuration context

src/Clide.UnitTests/Clide.UnitTests.csproj, src/Clide.UnitTests/CompositionSpec.cs, src/Clide.Vsix/Clide.Vsix.csproj, src/Clide.Vsix/FeatureFlags.pkgdef, src/Clide.Vsix/Properties/launchSettings.json, src/Clide.Vsix/source.extension.vsixmanifest, src/Clide/DiagnosticsLogProvider.cs, src/Clide/DiagnosticsLogging.cs, src/Clide/Interop/IVsFeatureFlags.cs, src/Clide/Interop/SVsFeatureFlags.cs, src/Clide/LegacyDiagnosticsLogProvider.cs, src/Directory.Build.props
Fixes AB#1025304, https://dev.azure.com/DevDiv/DevDiv/_workitems/edit/1025304
Whenever VS is started with `/log`, collect binary logs so Xamarin can do more
extensive troubleshooting when users provide logs. Applies *only* to Xamarin
projects and NETStandard projects with the `XamarinForms` capability, which
will limit its impact even though starting VS with `/log` is rare and a very
explicit opt-in action by a user.
=> Automatically log binary logs for Xamarin when /log requested

src/Clide.Core.Windows/UI/DialogWindowFactory.cs
In some rare cases, high DPI and VS might cause dialogs to be centered off-screen. 
To be safe, center on the owner window instead, which is always the visible IDE anyway, 
so it's also more appropriate.
=> Center the dialog on the owner, rather than the screen

build/azure-pipelines.yml, src/Clide.Windows/build/Clide.Windows.targets
Whenever Clide is built from source, it will be deployed and enabled in
the experimental instance of VS. Since the install path in the experimental
instance is predictable, we can automatically attempt to find it and offer
a better inner loop for contributors by replacing the nuget-provided Clide
references in their VSIX with the ones deployed by a locally build Clide.
This means contributing and consuming the contribution is as easy as
building Clide and then build as normal your extension. At some point when
the new APIs are available via nuget, you just bump the package reference
and can remove the experimental Clide from the local deploy folder at
`%LocalAppData%\Microsoft\VisualStudio\16.0_[INSTANCEID]Exp\Extensions\ClariusLabs\Clide\42.42.42`.
A quick `devenv /updateConfiguration …
=> Automatically detect the presence of an experimental Clide

src/Clide.Core.Windows/Events/ShellInitializedObservable.cs, src/Clide.UnitTests/Clide.UnitTests.csproj, src/Clide.UnitTests/CompositionSpec.cs, src/Clide.UnitTests/EnumerableExtensions.cs, src/Clide.UnitTests/Events/ShellInitializedObservableSpec.cs, src/Directory.Build.props, src/Directory.Build.targets
This heavy dependency was used very sparingly and could be
replaced quite easily for the source-only RxFree instead.
The existing custom observable ShellInitializedObservable
was simplified by leveraging other built-in primitives, and
its unit tests continued to pass with the new changes.
=> Remove dependency on System.Reactive
